<a href="https://colab.research.google.com/github/PhinyadaPhen/data_viz_2022/blob/main/CRM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive #เชื่อมต่อ colab เข้ากับไดร์ฟในข้อมูล
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os #จัดการหาไฟล์ที่อยู่ในไดร์ฟ

In [6]:
path = '/content/drive/My Drive/DWDM2021_DATA'

In [9]:
data_crm = os.path.join(path,'ex.csv') #เอาพาร์ทที่อยู่ในไฟล์มาเชื่อมกับColab
print(data_crm)

/content/drive/My Drive/DWDM2021_DATA/ex.csv

In [11]:
crm = pd.read_csv(data_crm)
crm

,_id,รูปแบบการเดินทาง,วัตถุประสงค์,สาธารณะ/ส่วนบุคคล,หน่วยงาน,ยานพาหนะ/ท่า,วันที่,หน่วย,ปริมาณ
0,1,ทางถนน,การเดินทางระหว่างจังหวัด,สาธารณะ,บขส.,รถ ขบส. และ รถร่วม,2020-01-01T00:00:00,คน,233330.0
1,2,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,ทล.,รถยนต์เฉพาะ 4 ล้อ (10 จุดสำรวจ),2020-01-01T00:00:00,คัน,977347.0
2,3,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,ทล.,รถยนต์ทุกประเภท (10 จุดสำรวจ),2020-01-01T00:00:00,คัน,1072314.0
3,4,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,กทพ.,รถยนต์เฉพาะ 4 ล้อ (ทางด่วน),2020-01-01T00:00:00,คัน,1333059.0
4,5,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,กทพ.,รถยนต์ทุกประเภท (ทางด่วน),2020-01-01T00:00:00,คัน,1353179.0
...,...,...,...,...,...,...,...,...,...
32477,32478,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศยานดอนเมือง ขาออกประเทศ,2022-08-07T00:00:00,คน,5426.0
32478,32479,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศอื่น ๆ ของ ทอท.ขาเข้าประเทศ,2022-08-07T00:00:00,คน,5178.0
32479,32480,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศอื่น ๆ ของ ทอท. ขาออกประเทศ,2022-08-07T00:00:00,คน,4800.0
32480,32481,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทย.,ท่าอากาศยานภูมิภาค ขาเข้าประเทศ,2022-08-07T00:00:00,คน,185.0
32481,32482,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทย.,ท่าอากาศยานภูมิภาค ขาออกประเทศ,2022-08-07T00:00:00,คน,183.0

In [20]:
patternn = crm.groupby('ยานพาหนะ/ท่า').size().reset_index(name='จำนวน')
patternn

                           ยานพาหนะ/ท่า  จำนวน
0                   ท่าอากาศยานดอนเมือง    950
1       ท่าอากาศยานดอนเมือง ขาออกประเทศ    950
2      ท่าอากาศยานดอนเมือง ขาเข้าประเทศ    950
3                    ท่าอากาศยานภูมิภาค    950
4        ท่าอากาศยานภูมิภาค ขาออกประเทศ    950
5       ท่าอากาศยานภูมิภาค ขาเข้าประเทศ    950
6                       ท่าอากาศยานสมุย    274
7                 ท่าอากาศยานสุวรรณภูมิ    950
8     ท่าอากาศยานสุวรรณภูมิ ขาออกประเทศ    950
9    ท่าอากาศยานสุวรรณภูมิ ขาเข้าประเทศ    950
10                  ท่าอากาศยานอู่ตะเภา    274
11              ท่าอากาศอื่น ๆ ของ ทอท.    950
12  ท่าอากาศอื่น ๆ ของ ทอท. ขาออกประเทศ    950
13  ท่าอากาศอื่น ๆ ของ ทอท.ขาเข้าประเทศ    950
14        ท่าเรือด่านชายแดน ขาออกประเทศ    874
15       ท่าเรือด่านชายแดน ขาเข้าประเทศ    859
16                   รถ ขบส. และ รถร่วม    950
17                  รถ บขส. ขาออกประเทศ     85
18                 รถ บขส. ขาเข้าประเทศ     85
19        รถยนต์ทุกประเภท (10 จุดสำรวจ)    950
20            รถยนต์ทุกประเภท (ทางด่วน)    950
21      รถยนต์เฉพาะ 4 ล้อ (10 จุดสำรวจ)    950
22          รถยนต์เฉพาะ 4 ล้อ (ทางด่วน)    950
23                      รถร่วม (หมวด 1)    950
24                             รถหมวด 3    890
25                             รถหมวด 4    890
26                         รถเมล์ ขสมก.    950
27           รถเอกชนเส้นปฏิรูป (หมวด 1)    870
28                                 รถไฟ    950
29       รถไฟ ขาออกประเทศ (ปาดังเบซาร์)     41
30      รถไฟ ขาเข้าประเทศ (ปาดังเบซาร์)     41
31                          รถไฟฟ้า ARL    950
32                          รถไฟฟ้า BTS    950
33                  รถไฟฟ้าสายสีน้ำเงิน    950
34                     รถไฟฟ้าสายสีม่วง    950
35                         รถไฟสายสีแดง    371
36                 เรือข้ามฟากเจ้าพระยา    804
37                       เรือคลองแสนแสบ    950
38                    เรือด่วนเจ้าพระยา    950
39                          เรือภูมิภาค    967
40                   เรือไฟฟ้าเจ้าพระยา    457

In [13]:
patternn1 = crm.groupby('วัตถุประสงค์').size().reset_index(name='จำนวน')
patternn1

                     วัตถุประสงค์  จำนวน
0  การเดินทางภายในจังหวัด/กรุงเทพ  11942
1        การเดินทางระหว่างจังหวัด  10955
2         การเดินทางระหว่างประเทศ   9585