<a href="https://colab.research.google.com/github/PhinyadaPhen/data_viz_2022/blob/main/CRM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive #เชื่อมต่อ colab เข้ากับไดร์ฟในข้อมูล
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os #จัดการหาไฟล์ที่อยู่ในไดร์ฟ

In [4]:
path = '/content/drive/My Drive/DWDM2021_DATA'

In [5]:
data_crm = os.path.join(path,'ex.csv') #เอาพาร์ทที่อยู่ในไฟล์มาเชื่อมกับColab
print(data_crm)

/content/drive/My Drive/DWDM2021_DATA/ex.csv

In [6]:
crm = pd.read_csv(data_crm)
crm

,_id,รูปแบบการเดินทาง,วัตถุประสงค์,สาธารณะ/ส่วนบุคคล,หน่วยงาน,ยานพาหนะ/ท่า,วันที่,หน่วย,ปริมาณ
0,1,ทางถนน,การเดินทางระหว่างจังหวัด,สาธารณะ,บขส.,รถ ขบส. และ รถร่วม,2020-01-01T00:00:00,คน,233330.0
1,2,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,ทล.,รถยนต์เฉพาะ 4 ล้อ (10 จุดสำรวจ),2020-01-01T00:00:00,คัน,977347.0
2,3,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,ทล.,รถยนต์ทุกประเภท (10 จุดสำรวจ),2020-01-01T00:00:00,คัน,1072314.0
3,4,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,กทพ.,รถยนต์เฉพาะ 4 ล้อ (ทางด่วน),2020-01-01T00:00:00,คัน,1333059.0
4,5,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,กทพ.,รถยนต์ทุกประเภท (ทางด่วน),2020-01-01T00:00:00,คัน,1353179.0
...,...,...,...,...,...,...,...,...,...
32477,32478,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศยานดอนเมือง ขาออกประเทศ,2022-08-07T00:00:00,คน,5426.0
32478,32479,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศอื่น ๆ ของ ทอท.ขาเข้าประเทศ,2022-08-07T00:00:00,คน,5178.0
32479,32480,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศอื่น ๆ ของ ทอท. ขาออกประเทศ,2022-08-07T00:00:00,คน,4800.0
32480,32481,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทย.,ท่าอากาศยานภูมิภาค ขาเข้าประเทศ,2022-08-07T00:00:00,คน,185.0
32481,32482,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทย.,ท่าอากาศยานภูมิภาค ขาออกประเทศ,2022-08-07T00:00:00,คน,183.0

In [20]:
data1all_alldb = crm[crm['รูปแบบการเดินทาง']=='ทางถนน']
   # ชี้ข้อมูลคอลัมน์ที่ต้องการ
data1all_alldb

,_id,รูปแบบการเดินทาง,วัตถุประสงค์,สาธารณะ/ส่วนบุคคล,หน่วยงาน,ยานพาหนะ/ท่า,วันที่,หน่วย,ปริมาณ
0,1,ทางถนน,การเดินทางระหว่างจังหวัด,สาธารณะ,บขส.,รถ ขบส. และ รถร่วม,2020-01-01T00:00:00,คน,233330.0
1,2,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,ทล.,รถยนต์เฉพาะ 4 ล้อ (10 จุดสำรวจ),2020-01-01T00:00:00,คัน,977347.0
2,3,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,ทล.,รถยนต์ทุกประเภท (10 จุดสำรวจ),2020-01-01T00:00:00,คัน,1072314.0
3,4,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,กทพ.,รถยนต์เฉพาะ 4 ล้อ (ทางด่วน),2020-01-01T00:00:00,คัน,1333059.0
4,5,ทางถนน,การเดินทางระหว่างจังหวัด,ส่วนบุคคล,กทพ.,รถยนต์ทุกประเภท (ทางด่วน),2020-01-01T00:00:00,คัน,1353179.0
...,...,...,...,...,...,...,...,...,...
32448,32449,ทางถนน,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,ขสมก.,รถเมล์ ขสมก.,2022-08-07T00:00:00,คน,513031.0
32449,32450,ทางถนน,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,ขสมก.,รถร่วม (หมวด 1),2022-08-07T00:00:00,คน,62150.0
32450,32451,ทางถนน,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,ขบ.,รถเอกชนเส้นปฏิรูป (หมวด 1),2022-08-07T00:00:00,คน,121163.0
32468,32469,ทางถนน,การเดินทางระหว่างประเทศ,สาธารณะ,บขส.,รถ บขส. ขาเข้าประเทศ,2022-08-07T00:00:00,คน,603.0
32469,32470,ทางถนน,การเดินทางระหว่างประเทศ,สาธารณะ,บขส.,รถ บขส. ขาออกประเทศ,2022-08-07T00:00:00,คน,786.0

In [21]:
crm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32482 entries, 0 to 32481
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   _id                32482 non-null  int64
 1   รูปแบบการเดินทาง   32482 non-null  object
 2   วัตถุประสงค์       32482 non-null  object
 3   สาธารณะ/ส่วนบุคคล  32482 non-null  object
 4   หน่วยงาน           32482 non-null  object
 5   ยานพาหนะ/ท่า       32482 non-null  object
 6   วันที่             32482 non-null  object
 7   หน่วย              32482 non-null  object
 8   ปริมาณ             32482 non-null  float64
dtypes: float64(1), int64(1), object(7)
memory usage: 2.2+ MB

In [22]:
data1all_alldb.to_csv('data1all_alldb.csv', encoding='utf-8')

In [23]:
waaaa = crm[crm['รูปแบบการเดินทาง']=='ทางน้ำ']
   # ชี้ข้อมูลคอลัมน์ที่ต้องการ
waaaa

,_id,รูปแบบการเดินทาง,วัตถุประสงค์,สาธารณะ/ส่วนบุคคล,หน่วยงาน,ยานพาหนะ/ท่า,วันที่,หน่วย,ปริมาณ
7,8,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือด่วนเจ้าพระยา,2020-01-01T00:00:00,คน,29518.0
8,9,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือคลองแสนแสบ,2020-01-01T00:00:00,คน,20420.0
9,10,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือภูมิภาค,2020-01-01T00:00:00,คน,222640.0
34,35,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือด่วนเจ้าพระยา,2020-01-02T00:00:00,คน,30794.0
35,36,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือคลองแสนแสบ,2020-01-02T00:00:00,คน,35430.0
...,...,...,...,...,...,...,...,...,...
32453,32454,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือข้ามฟากเจ้าพระยา,2022-08-07T00:00:00,คน,13608.0
32454,32455,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือไฟฟ้าเจ้าพระยา,2022-08-07T00:00:00,คน,1675.0
32455,32456,ทางน้ำ,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,จท.,เรือภูมิภาค,2022-08-07T00:00:00,คน,88394.0
32472,32473,ทางน้ำ,การเดินทางระหว่างประเทศ,สาธารณะ,จท.,ท่าเรือด่านชายแดน ขาเข้าประเทศ,2022-08-07T00:00:00,คน,3.0
32473,32474,ทางน้ำ,การเดินทางระหว่างประเทศ,สาธารณะ,จท.,ท่าเรือด่านชายแดน ขาออกประเทศ,2022-08-07T00:00:00,คน,0.0

In [25]:
waaaa.to_csv('waaaa.csv', encoding='utf-8')

In [26]:
train = crm[crm['รูปแบบการเดินทาง']=='ทางราง']
   # ชี้ข้อมูลคอลัมน์ที่ต้องการ
train

,_id,รูปแบบการเดินทาง,วัตถุประสงค์,สาธารณะ/ส่วนบุคคล,หน่วยงาน,ยานพาหนะ/ท่า,วันที่,หน่วย,ปริมาณ
10,11,ทางราง,การเดินทางระหว่างจังหวัด,สาธารณะ,รฟท.,รถไฟ,2020-01-01T00:00:00,คน,115975.0
11,12,ทางราง,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,รฟม.,รถไฟฟ้าสายสีน้ำเงิน,2020-01-01T00:00:00,คน,236053.0
12,13,ทางราง,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,รฟม.,รถไฟฟ้าสายสีม่วง,2020-01-01T00:00:00,คน,23135.0
13,14,ทางราง,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,รฟฟท.,รถไฟฟ้า ARL,2020-01-01T00:00:00,คน,48790.0
14,15,ทางราง,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,กทม.,รถไฟฟ้า BTS,2020-01-01T00:00:00,คน,461400.0
...,...,...,...,...,...,...,...,...,...
32459,32460,ทางราง,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,รฟฟท.,รถไฟฟ้า ARL,2022-08-07T00:00:00,คน,35716.0
32460,32461,ทางราง,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,กทม.,รถไฟฟ้า BTS,2022-08-07T00:00:00,คน,427680.0
32461,32462,ทางราง,การเดินทางภายในจังหวัด/กรุงเทพ,สาธารณะ,รฟฟท.,รถไฟสายสีแดง,2022-08-07T00:00:00,คน,10879.0
32470,32471,ทางราง,การเดินทางระหว่างประเทศ,สาธารณะ,รฟท.,รถไฟ ขาเข้าประเทศ (ปาดังเบซาร์),2022-08-07T00:00:00,คน,131.0
32471,32472,ทางราง,การเดินทางระหว่างประเทศ,สาธารณะ,รฟท.,รถไฟ ขาออกประเทศ (ปาดังเบซาร์),2022-08-07T00:00:00,คน,296.0

In [27]:
train.to_csv('train.csv', encoding='utf-8')

In [28]:
air = crm[crm['รูปแบบการเดินทาง']=='ทางอากาศ']
   # ชี้ข้อมูลคอลัมน์ที่ต้องการ
air

,_id,รูปแบบการเดินทาง,วัตถุประสงค์,สาธารณะ/ส่วนบุคคล,หน่วยงาน,ยานพาหนะ/ท่า,วันที่,หน่วย,ปริมาณ
15,16,ทางอากาศ,การเดินทางระหว่างจังหวัด,สาธารณะ,ทอท.,ท่าอากาศยานสุวรรณภูมิ,2020-01-01T00:00:00,คน,14674.0
16,17,ทางอากาศ,การเดินทางระหว่างจังหวัด,สาธารณะ,ทอท.,ท่าอากาศยานดอนเมือง,2020-01-01T00:00:00,คน,31100.0
17,18,ทางอากาศ,การเดินทางระหว่างจังหวัด,สาธารณะ,ทอท.,ท่าอากาศอื่น ๆ ของ ทอท.,2020-01-01T00:00:00,คน,32892.0
18,19,ทางอากาศ,การเดินทางระหว่างจังหวัด,สาธารณะ,ทย.,ท่าอากาศยานภูมิภาค,2020-01-01T00:00:00,คน,24012.0
19,20,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศยานสุวรรณภูมิ ขาเข้าประเทศ,2020-01-01T00:00:00,คน,82591.0
...,...,...,...,...,...,...,...,...,...
32477,32478,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศยานดอนเมือง ขาออกประเทศ,2022-08-07T00:00:00,คน,5426.0
32478,32479,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศอื่น ๆ ของ ทอท.ขาเข้าประเทศ,2022-08-07T00:00:00,คน,5178.0
32479,32480,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทอท.,ท่าอากาศอื่น ๆ ของ ทอท. ขาออกประเทศ,2022-08-07T00:00:00,คน,4800.0
32480,32481,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทย.,ท่าอากาศยานภูมิภาค ขาเข้าประเทศ,2022-08-07T00:00:00,คน,185.0
32481,32482,ทางอากาศ,การเดินทางระหว่างประเทศ,สาธารณะ,ทย.,ท่าอากาศยานภูมิภาค ขาออกประเทศ,2022-08-07T00:00:00,คน,183.0

In [29]:
air.to_csv('air.csv', encoding='utf-8')

In [7]:
patternn = crm.groupby('ยานพาหนะ/ท่า').size().reset_index(name='จำนวน')
patternn

                           ยานพาหนะ/ท่า  จำนวน
0                   ท่าอากาศยานดอนเมือง    950
1       ท่าอากาศยานดอนเมือง ขาออกประเทศ    950
2      ท่าอากาศยานดอนเมือง ขาเข้าประเทศ    950
3                    ท่าอากาศยานภูมิภาค    950
4        ท่าอากาศยานภูมิภาค ขาออกประเทศ    950
5       ท่าอากาศยานภูมิภาค ขาเข้าประเทศ    950
6                       ท่าอากาศยานสมุย    274
7                 ท่าอากาศยานสุวรรณภูมิ    950
8     ท่าอากาศยานสุวรรณภูมิ ขาออกประเทศ    950
9    ท่าอากาศยานสุวรรณภูมิ ขาเข้าประเทศ    950
10                  ท่าอากาศยานอู่ตะเภา    274
11              ท่าอากาศอื่น ๆ ของ ทอท.    950
12  ท่าอากาศอื่น ๆ ของ ทอท. ขาออกประเทศ    950
13  ท่าอากาศอื่น ๆ ของ ทอท.ขาเข้าประเทศ    950
14        ท่าเรือด่านชายแดน ขาออกประเทศ    874
15       ท่าเรือด่านชายแดน ขาเข้าประเทศ    859
16                   รถ ขบส. และ รถร่วม    950
17                  รถ บขส. ขาออกประเทศ     85
18                 รถ บขส. ขาเข้าประเทศ     85
19        รถยนต์ทุกประเภท (10 จุดสำรวจ)    950
20            รถยนต์ทุกประเภท (ทางด่วน)    950
21      รถยนต์เฉพาะ 4 ล้อ (10 จุดสำรวจ)    950
22          รถยนต์เฉพาะ 4 ล้อ (ทางด่วน)    950
23                      รถร่วม (หมวด 1)    950
24                             รถหมวด 3    890
25                             รถหมวด 4    890
26                         รถเมล์ ขสมก.    950
27           รถเอกชนเส้นปฏิรูป (หมวด 1)    870
28                                 รถไฟ    950
29       รถไฟ ขาออกประเทศ (ปาดังเบซาร์)     41
30      รถไฟ ขาเข้าประเทศ (ปาดังเบซาร์)     41
31                          รถไฟฟ้า ARL    950
32                          รถไฟฟ้า BTS    950
33                  รถไฟฟ้าสายสีน้ำเงิน    950
34                     รถไฟฟ้าสายสีม่วง    950
35                         รถไฟสายสีแดง    371
36                 เรือข้ามฟากเจ้าพระยา    804
37                       เรือคลองแสนแสบ    950
38                    เรือด่วนเจ้าพระยา    950
39                          เรือภูมิภาค    967
40                   เรือไฟฟ้าเจ้าพระยา    457

In [24]:
patternn1 = crm.groupby('รูปแบบการเดินทาง').size().reset_index(name='จำนวน')
patternn1

  รูปแบบการเดินทาง  จำนวน
0           ทางถนน   9470
1           ทางน้ำ   5861
2           ทางราง   5203
3         ทางอากาศ  11948